<h2>Simulation and analysis of the card game "No Thanks"</h2>

Import game simulator code from nothx.py. Also import numpy for data analysis and matpltlib for plots.

In [14]:
from nothx import Table, Deck, Player
import numpy as np
import matplotlib.pyplot as plt

Select the number of players and the number of games to simulate.

In [7]:
num_players = 3
num_games = 10

Run the simulation. For the initial analysis, retain data only from the winners.

The output of the Table.score() function, assigned to game_data in the code below, is a list of lists, or a list of *features* in data science parlance. The first index corresponds to the player and the second to various features (attributes) associated with the player. The feature indexed by 1 tells whether the player lost (0), won (1), or tied for the win (2). Here, game data is retained for those who won or tied. The last column of the feature-list is a list of cards in the player's final hand, in the order in which they were obtained during the game. For ease of working with the data (since the other features are single values, not lists), the "cards" feature is separated into a new list of lists.

In [8]:
cards = []
wins = []
for i in range(num_games):
    mytable = Table(num_ai_players = num_players, verbose = 0)
    mytable.play()
    game_data = mytable.score()
    for j in range(num_players):
        if game_data[j][1] > 0:
            cards.append(game_data[j].pop())
            wins.append(game_data[j])
winners = np.array(wins)

Inspect the "winners" features.

<table>
   <tr>
      <td>Column Index</td> <td>Description</td>
   </tr>
   <tr>
      <td><div align="center">0</div></td> <td>Player position (indexed from 0, i.e. the player who went first has position 0)</td>
   </tr>
   <tr>
      <td><div align="center">1</div></td> <td>Lost = 0<br>Won = 1<br>Tied = 2<br>Since data for the players who lost was not retained, this column should be populated entirely with "1"s and "2"s.</td>
   </tr>
   <tr>
      <td><div align="center">2</div></td> <td>Final score</td>
   </tr>
   <tr>
      <td><div align="center">3</div></td> <td>Card threshold value</td>
   </tr>
   <tr>
      <td><div align="center">4</div></td> <td>Token threshold value</td>
   </tr>
   <tr>
      <td><div align="center">5</div></td> <td>"Effective value" threshold value</td>
   </tr>
   <tr>
      <td><div align="center">6</div></td> <td>The number of times a player passed before taking her first card</td>
   </tr>
   <tr>
      <td><div align="center">7</div></td> <td>The minimum number of tokens the player ever had during the game</td>
   </tr>
   <tr>
      <td><div align="center">8</div></td> <td>The maximum number of tokens the player ever had during the game</td>
   </tr>
</table>

In [9]:
print(winners)

[[ 1  1 17 28  8  3  0  0 22]
 [ 0  1 47 22  3  2  0  0 27]
 [ 2  1 33 21  9  2  0  0 21]
 [ 0  1 63 34  1  3  0  0 25]
 [ 1  1 42 34  3  2  0  3 26]
 [ 0  1 27 20  9  3  0  0 26]
 [ 2  1 29 24  1  4  0  1 26]
 [ 1  1 31 12 10  3  0  2 29]
 [ 0  1 29 14  3  4  0  5 29]
 [ 0  1  2 32  1  4  0  3 31]]


Investigate the range of values present in some of the feature columns.

In [15]:
low_max_tokens = min(winners[:,8])
high_max_tokens = max(winners[:,8])
print("Winners had between", low_max_tokens, "and", high_max_tokens, "as their maximum number of tokens.")
low_min_tokens = min(winners[:,7])
high_min_tokens = max(winners[:,7])
print("winners had between", low_min_tokens, "and", high_min_tokens, "as their minimum number of tokens.")

Winners had between 21 and 31 as their maximum number of tokens.
winners had between 0 and 5 as their minimum number of tokens.


Does player position confer an advantage?

In [19]:
pos = list(winners[:,0])
positions = []
for i in range(num_players):
    positions.append(pos.count(i))
print(positions)


[5, 3, 2]
